---
title: "Homework 5"
author: Akanksha Nalatwad
output: html_document
---


```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r}
homicide_df=
  read_csv("homicide_data/homicide-data.csv") %>% 
  mutate(
    city_state= str_c(city, state, sep = "_"),
    resolved= case_when(
      disposition=="Closed without arrest"~ "unsolved",
      disposition=="Open/No arrest"       ~ "unsolved",
      disposition== "Closed by arrest"      ~"solved"
      )
  ) %>% 
  select(city_state,resolved) %>% 
  filter(city_state !="Tulsa_AL")
```
Let's look at this a bit

```{r}
aggregate_df=
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total=n(),
    hom_unsolved= sum(resolved=="unsolved")
  )
  
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter (city_state=="Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter (city_state=="Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()
```

 
Try to iterate.....

```{r}
results_df=
aggregate_df %>% 
  mutate(
    prop_tests= map2(.x=hom_unsolved, .y=hom_total, ~prop.test(x=.x, n=.y)),
    tidy_tests= map (.x= prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```


```{r}
results_df %>% 
  mutate(city_state=fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x=city_state, y=estimate))+
  geom_point()+
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high))+
  theme(axis.text.x= element_text (angle=90, vjust=0.5, hjust=1))
```
## Problem 2

Data Mapping and Tidying


```{r}
path_df=
tibble(
  path= list.files("lda_data")
) %>% 
  mutate(path=str_c("lda_data/", path),
         path_2=path,
         data=map(path, read_csv)) %>% 
  separate(col=path_2, into=c("path_a", "path_b"), sep=9, remove=T) %>% 
  separate(col=path_b, into= c("arm", "id_number", sep=3)) %>% 
  select(-path_a,-c(5)) %>% 
  mutate(
  arm=str_replace(arm,"exp","Experimental"), 
  arm=str_replace(arm, "con", "Control")) %>% 
  within(Arm_ID <- paste(arm, id_number, sep='_')) %>% 
  select(-id_number) %>% 
  unnest(data) %>%
 pivot_longer(week_1:week_8,
              names_to="week_number",
              values_to="weekly_observation"
            ) %>% 
  mutate(
    week_number= str_replace(week_number, "week_", "")
  )
```

## Spaghetti Plot
```{r}
plot_p=
ggplot(data = path_df, aes(x = week_number, y = weekly_observation, group = Arm_ID))+
   geom_line(aes(linetype=arm))
```

## Problem 3

